project:
  type: website
  output-dir: "."

website:
  title: "Data Finance Project"
  navbar:
    left:
      - href: index.qmd
        text: Introdução
      - href: analise_acoes.qmd
      - href: teste.qmd
      - href: markowitz.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css      # CSS global para todo o site
    toc: true