project:
  type: website
  output-dir: "."
  
website:
  title: "Data Finance Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - analise_acoes.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



